# columns to be needed in dataset
columns:
  -  Chromosome
  -  Position
  -  Reference Allele
  -  Alternate Allele
  -  Consequence
  -  IMPACT
  -  SYMBOL
  -  Feature
  -  BIOTYPE
  -  SIFT
  -  PolyPhen
  -  CADD_PHRED
  -  CADD_RAW
  -  DANN_score
  -  Eigen-PC-phred_coding
  -  Eigen-PC-raw_coding
  -  Eigen-PC-raw_coding_rankscore
  -  Eigen-phred_coding
  -  Eigen-raw_coding
  -  Eigen-raw_coding_rankscore
  -  FATHMM_score
  -  GERP++_RS
  -  GenoCanyon_score
  -  LRT_score
  -  M-CAP_score
  -  MetaLR_score
  -  MetaSVM_score
  -  MutationAssessor_score
  -  MutationTaster_score
  -  PROVEAN_score
  -  SiPhy_29way_logOdds
  -  VEST4_score
  -  fathmm-MKL_coding_score
  -  integrated_fitCons_score
  -  phastCons100way_vertebrate
  -  phastCons30way_mammalian
  -  phyloP100way_vertebrate
  -  phyloP30way_mammalian
  -  GERP
  -  gnomADv3_AF
  -  gnomADv3_AF_afr
  -  gnomADv3_AF_afr_female
  -  gnomADv3_AF_afr_male
  -  gnomADv3_AF_ami
  -  gnomADv3_AF_ami_female
  -  gnomADv3_AF_ami_male
  -  gnomADv3_AF_amr
  -  gnomADv3_AF_amr_female
  -  gnomADv3_AF_amr_male
  -  gnomADv3_AF_asj
  -  gnomADv3_AF_asj_female
  -  gnomADv3_AF_asj_male
  -  gnomADv3_AF_eas
  -  gnomADv3_AF_eas_female
  -  gnomADv3_AF_eas_male
  -  gnomADv3_AF_female
  -  gnomADv3_AF_fin
  -  gnomADv3_AF_fin_female
  -  gnomADv3_AF_fin_male
  -  gnomADv3_AF_male
  -  gnomADv3_AF_nfe
  -  gnomADv3_AF_nfe_female
  -  gnomADv3_AF_nfe_male
  -  gnomADv3_AF_oth
  -  gnomADv3_AF_oth_female
  -  gnomADv3_AF_oth_male
  -  gnomADv3_AF_raw
  -  gnomADv3_AF_sas
  -  gnomADv3_AF_sas_female
  -  gnomADv3_AF_sas_male
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  hgmd_class
<<<<<<< HEAD
  
=======

>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
ClinicalSignificance:
  -  DP
  -  DFP
  -  FP
  -  DM?
  -  DM
  -  Benign
  -  Benign/Likely_benign
  -  Pathogenic/Likely_pathogenic
  -  Pathogenic
  -  Likely_pathogenic
  -  Likely_benign

Clinsig_train:
  -  Pathogenic/Likely_pathogenic
  -  DM
  -  Benign
  -  Pathogenic
  -  Likely_benign
  -  Likely_pathogenic

Clinsig_test:

  -  DM?
  -  DP
  -  DFP
  -  FP
  -  Benign/Likely_benign


CLNREVSTAT: #https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/
  -  practice_guideline
  -  reviewed_by_expert_panel
  -  criteria_provided,_multiple_submitters,_no_conflicts
  -  criteria_provided,_single_submitter

col_conv:
<<<<<<< HEAD
=======
  -  MutationTaster_score
  -  MutationAssessor_score
  -  PROVEAN_score
  -  VEST4_score
  -  FATHMM_score
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
  -  GERP

ML_VAR:
  -  SYMBOL
  -  Feature
  -  Consequence
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  Chromosome
  -  Position
  -  Alternate Allele
  -  Reference Allele
  -  ID

var:
  -  SYMBOL
  -  Feature
  -  Consequence
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  Chromosome
  -  Position
  -  Alternate Allele
  -  Reference Allele

Consequence:
  -  missense_variant
<<<<<<< HEAD
  -  missense_variant&splice_region_variant 
=======
  -  missense_variant&splice_region_variant
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
  -  stop_gained
  -  start_lost&NMD_transcript_variant
  -  start_lost
  -  stop_gained&splice_region_variant
  -  stop_gained&NMD_transcript_variant
  -  missense_variant&splice_region_variant&NMD_transcript_variant
  -  stop_gained&splice_region_variant&NMD_transcript_variant
  -  start_lost&splice_region_variant
  -  stop_lost&splice_region_variant
  -  stop_lost&splice_region_variant&NMD_transcript_variant
  -  splice_donor_variant&missense_variant
  -  start_lost&splice_region_variant&NMD_transcript_variant

gnomad_columns:
  -  gnomADv3_AF
  -  gnomADv3_AF_afr
  -  gnomADv3_AF_afr_female
  -  gnomADv3_AF_afr_male
  -  gnomADv3_AF_ami
  -  gnomADv3_AF_ami_female
  -  gnomADv3_AF_ami_male
  -  gnomADv3_AF_amr
  -  gnomADv3_AF_amr_female
  -  gnomADv3_AF_amr_male
  -  gnomADv3_AF_asj
  -  gnomADv3_AF_asj_female
  -  gnomADv3_AF_asj_male
  -  gnomADv3_AF_eas
  -  gnomADv3_AF_eas_female
  -  gnomADv3_AF_eas_male
  -  gnomADv3_AF_female
  -  gnomADv3_AF_fin
  -  gnomADv3_AF_fin_female
  -  gnomADv3_AF_fin_male
  -  gnomADv3_AF_male
  -  gnomADv3_AF_nfe
  -  gnomADv3_AF_nfe_female
  -  gnomADv3_AF_nfe_male
  -  gnomADv3_AF_oth
  -  gnomADv3_AF_oth_female
  -  gnomADv3_AF_oth_male
  -  gnomADv3_AF_raw
  -  gnomADv3_AF_sas
  -  gnomADv3_AF_sas_female
  -  gnomADv3_AF_sas_male

<<<<<<< HEAD
nssnv_columns: 
=======
nssnv_columns:
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
  SIFT: 0.5
  PolyPhen: 0.5
  CADD_PHRED: 20
  MetaSVM_score: 0.5   # range - -2 to 3
  FATHMM_score: 0         #weighted for human inherited- disease mutations with Disease Ontology (FATHMMori). Scores range from -18.09 to 11.0. This is for coding and MKL for non-coding variants
  MutationAssessor_score: 0   #MutationAssessor functional impact combined score (MAori). The score ranges from -5.135 to 6.49 in dbNSFP.
  PROVEAN_score: 0           # range - -14 to 13.57
  VEST4_score: 0.5           # range - 0 to 1
  GERP: 0 #ranges from -12.36 to 6.18
  MutationTaster_score: 0.5
  DANN_score: 0.5
  Eigen-PC-phred_coding: 20
  Eigen-PC-raw_coding: 0   #functional annotations. input range - -3.252 to 8.426.
  Eigen-PC-raw_coding_rankscore: 0
  Eigen-phred_coding: 20
  Eigen-raw_coding: 0
  Eigen-raw_coding_rankscore: 0
  GERP++_RS: 0
  GenoCanyon_score: 0.5
  LRT_score: 0.5  #The score ranges from 0 to 1 and a larger score signifies that the codon is more constrained or a NS is more likely to be deleterious.
  M-CAP_score: 0.5   # range - 0 to 1
  MetaLR_score: 0.5  # range - 0 to 1
  SiPhy_29way_logOdds: 15 # input range - 0 to 33.272. SiPhy score based on 29 mammals genomes. The larger the score, the more conserved the site.
  fathmm-MKL_coding_score: 0.5  # range - 0 to 1. This is for non-coding variants - functional prediction tool
  integrated_fitCons_score: 0.5 # range - 0 to 1
  phastCons100way_vertebrate: 0.5
  phastCons30way_mammalian: 0.5
  phyloP100way_vertebrate: 20
  phyloP30way_mammalian: 20
  IMPACT_HIGH: 0
  IMPACT_LOW: 0
  IMPACT_MODERATE: 0
  IMPACT_MODIFIER: 0
  BIOTYPE_RNase_MRP_RNA: 0
  BIOTYPE_RNase_P_RNA: 0
  BIOTYPE_antisense_RNA: 0
  BIOTYPE_guide_RNA: 0
  BIOTYPE_lncRNA: 0
  BIOTYPE_miRNA: 0
  BIOTYPE_misc_RNA: 0
  BIOTYPE_ncRNA_pseudogene: 0
  BIOTYPE_protein_coding: 0
  BIOTYPE_scRNA: 0
  BIOTYPE_snRNA: 0
  BIOTYPE_snoRNA: 0
  BIOTYPE_telomerase_RNA: 0
  BIOTYPE_transcribed_pseudogene: 0
  BIOTYPE_nonsense_mediated_decay: 0
  BIOTYPE_polymorphic_pseudogene: 0
  BIOTYPE_IG_C_gene: 0
  BIOTYPE_non_stop_decay: 0

<<<<<<< HEAD
non_nssnv_columns:  
=======
non_nssnv_columns:
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
  CADD_PHRED: 20
  GERP: 0
  IMPACT_HIGH: 0
  IMPACT_LOW: 0
  IMPACT_MODERATE: 0
  IMPACT_MODIFIER: 0
  BIOTYPE_RNase_MRP_RNA: 0
  BIOTYPE_RNase_P_RNA: 0
  BIOTYPE_antisense_RNA: 0
  BIOTYPE_guide_RNA: 0
  BIOTYPE_lncRNA: 0
  BIOTYPE_miRNA: 0
  BIOTYPE_misc_RNA: 0
  BIOTYPE_protein_coding: 0
  BIOTYPE_snRNA: 0
  BIOTYPE_snoRNA: 0
  BIOTYPE_transcribed_pseudogene: 0

<<<<<<< HEAD
nssnv_median_3_0_1: 
=======
nssnv_median_3_0_1:
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
  gnomADv3_AF: 0
  SIFT: 0.02
  PolyPhen: 0.757
  CADD_PHRED: 25.3
  DANN_score: 0.995325924
  Eigen-PC-phred_coding: 4.859703
  Eigen-PC-raw_coding: 0.465540408
  FATHMM_score: -1.26
  GERP++_RS: 4.73
  GenoCanyon_score: 0.999998451
  LRT_score: 2.30E-05
  M-CAP_score: 0.226631
  MetaSVM_score: -0.1847
  MutationAssessor_score: 2.215
  MutationTaster_score: 1
  PROVEAN_score: -2.88
  SiPhy_29way_logOdds: 13.8644
  VEST4_score: 0.762
  fathmm-MKL_coding_score: 0.94206
  integrated_fitCons_score: 0.675202
  phastCons100way_vertebrate: 1
  phastCons30way_mammalian: 0.99
  phyloP100way_vertebrate: 4.564
  phyloP30way_mammalian: 1.026
  GERP: 5.67
  IMPACT_HIGH: 0
  BIOTYPE_IG_C_gene: 0
  BIOTYPE_non_stop_decay: 0
  BIOTYPE_polymorphic_pseudogene: 0
<<<<<<< HEAD
  BIOTYPE_protein_coding: 1
=======
  BIOTYPE_protein_coding: 1
>>>>>>> bcf8822dc39ff4415e7d8b84138b7463ca901555
