name: training

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8.5
  - pandas=1.2.1
  - numpy=1.20.2
  #- optuna=2.5.0
  - scikit-learn=0.24.1
  - imbalanced-learn=0.7.0
  - scipy=1.6.3
  - shap=0.37.0
  - pip
  - gpy=1.9.9
  - scikit-optimize=0.8.1
  - hyperopt=0.2.5
  #- tune-sklearn=0.2.1
  - pip:
    - ray==1.4.0
    - ray[tune]
    - tensorflow-gpu==2.3
    - lz4==3.1.3
